language: node_js

git:
  depth: 1

node_js:
  - '8'

before_install:
  - nvm install-latest-npm

install:
  - cd client/admin && npm install ms
  - npm install --only=dev

script:
  - npm run lint

cache:
  directories:
    - client/admin/node_modules

  sudo: false
